---
driver:
  name: vagrant
  network:
    - ['forwarded_port', {guest: 3000, host: 3000}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[mimo::default]
    attributes:
