name             'mimo'
maintainer       'Rakuten, Inc.'
maintainer_email 'ops@rakops.com'
license          'Apache 2.0'
description      'Installs/Configures mimo'
long_description 'Installs/Configures mimo'
version          '0.1.0'
